# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"%\n\x11storedata_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"#\n\x0fgetdata_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"0\n\x17\x66ragment_status_request\x12\x15\n\rfragment_name\x18\x01 \x01(\t\"\'\n\x0bStorageNode\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"5\n\rTask11Request\x12\x11\n\tfile_uuid\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"!\n\x0eTask11Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"^\n\rTask12Request\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x04\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\x12)\n\x13nodes_to_forward_to\x18\x03 \x03(\x0b\x32\x0c.StorageNode\"!\n\x0eTask12Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"l\n\x17\x66hdfs_storedata_request\x12\x11\n\tstripe_id\x18\x01 \x01(\x04\x12\x13\n\x0b\x66ragment_id\x18\x02 \x01(\x04\x12)\n\x13nodes_to_forward_to\x18\x03 \x03(\x0b\x32\x0c.StorageNode\"2\n\x11HeartBeatResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x10\n\x08is_alive\x18\x02 \x01(\x08\"@\n\x18\x66hdfs_storedata_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bstorage_ids\x18\x02 \x03(\t\"e\n\x18\x66ragment_status_response\x12\x15\n\rfragment_name\x18\x01 \x01(\t\x12\x12\n\nis_present\x18\x02 \x01(\x08\x12\x0f\n\x07node_id\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"-\n\x06header\x12#\n\x0crequest_type\x18\x01 \x01(\x0e\x32\r.request_type\"f\n\x18recode_fragments_request\x12\x15\n\rfragment_name\x18\x01 \x01(\t\x12\x14\n\x0csymbol_count\x18\x02 \x01(\x05\x12\x1d\n\x15output_fragment_count\x18\x03 \x01(\x05*u\n\x0crequest_type\x12\x17\n\x13\x46RAGMENT_STATUS_REQ\x10\x00\x12\x15\n\x11\x46RAGMENT_DATA_REQ\x10\x01\x12\x1b\n\x17STORE_FRAGMENT_DATA_REQ\x10\x02\x12\x18\n\x14RECODE_FRAGMENTS_REQ\x10\x03\x62\x06proto3')

_REQUEST_TYPE = DESCRIPTOR.enum_types_by_name['request_type']
request_type = enum_type_wrapper.EnumTypeWrapper(_REQUEST_TYPE)
FRAGMENT_STATUS_REQ = 0
FRAGMENT_DATA_REQ = 1
STORE_FRAGMENT_DATA_REQ = 2
RECODE_FRAGMENTS_REQ = 3


_STOREDATA_REQUEST = DESCRIPTOR.message_types_by_name['storedata_request']
_GETDATA_REQUEST = DESCRIPTOR.message_types_by_name['getdata_request']
_FRAGMENT_STATUS_REQUEST = DESCRIPTOR.message_types_by_name['fragment_status_request']
_STORAGENODE = DESCRIPTOR.message_types_by_name['StorageNode']
_TASK11REQUEST = DESCRIPTOR.message_types_by_name['Task11Request']
_TASK11RESPONSE = DESCRIPTOR.message_types_by_name['Task11Response']
_TASK12REQUEST = DESCRIPTOR.message_types_by_name['Task12Request']
_TASK12RESPONSE = DESCRIPTOR.message_types_by_name['Task12Response']
_FHDFS_STOREDATA_REQUEST = DESCRIPTOR.message_types_by_name['fhdfs_storedata_request']
_HEARTBEATRESPONSE = DESCRIPTOR.message_types_by_name['HeartBeatResponse']
_FHDFS_STOREDATA_RESPONSE = DESCRIPTOR.message_types_by_name['fhdfs_storedata_response']
_FRAGMENT_STATUS_RESPONSE = DESCRIPTOR.message_types_by_name['fragment_status_response']
_HEADER = DESCRIPTOR.message_types_by_name['header']
_RECODE_FRAGMENTS_REQUEST = DESCRIPTOR.message_types_by_name['recode_fragments_request']
storedata_request = _reflection.GeneratedProtocolMessageType('storedata_request', (_message.Message,), {
  'DESCRIPTOR' : _STOREDATA_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:storedata_request)
  })
_sym_db.RegisterMessage(storedata_request)

getdata_request = _reflection.GeneratedProtocolMessageType('getdata_request', (_message.Message,), {
  'DESCRIPTOR' : _GETDATA_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:getdata_request)
  })
_sym_db.RegisterMessage(getdata_request)

fragment_status_request = _reflection.GeneratedProtocolMessageType('fragment_status_request', (_message.Message,), {
  'DESCRIPTOR' : _FRAGMENT_STATUS_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:fragment_status_request)
  })
_sym_db.RegisterMessage(fragment_status_request)

StorageNode = _reflection.GeneratedProtocolMessageType('StorageNode', (_message.Message,), {
  'DESCRIPTOR' : _STORAGENODE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:StorageNode)
  })
_sym_db.RegisterMessage(StorageNode)

Task11Request = _reflection.GeneratedProtocolMessageType('Task11Request', (_message.Message,), {
  'DESCRIPTOR' : _TASK11REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Task11Request)
  })
_sym_db.RegisterMessage(Task11Request)

Task11Response = _reflection.GeneratedProtocolMessageType('Task11Response', (_message.Message,), {
  'DESCRIPTOR' : _TASK11RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Task11Response)
  })
_sym_db.RegisterMessage(Task11Response)

Task12Request = _reflection.GeneratedProtocolMessageType('Task12Request', (_message.Message,), {
  'DESCRIPTOR' : _TASK12REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Task12Request)
  })
_sym_db.RegisterMessage(Task12Request)

Task12Response = _reflection.GeneratedProtocolMessageType('Task12Response', (_message.Message,), {
  'DESCRIPTOR' : _TASK12RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Task12Response)
  })
_sym_db.RegisterMessage(Task12Response)

fhdfs_storedata_request = _reflection.GeneratedProtocolMessageType('fhdfs_storedata_request', (_message.Message,), {
  'DESCRIPTOR' : _FHDFS_STOREDATA_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:fhdfs_storedata_request)
  })
_sym_db.RegisterMessage(fhdfs_storedata_request)

HeartBeatResponse = _reflection.GeneratedProtocolMessageType('HeartBeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeatResponse)
  })
_sym_db.RegisterMessage(HeartBeatResponse)

fhdfs_storedata_response = _reflection.GeneratedProtocolMessageType('fhdfs_storedata_response', (_message.Message,), {
  'DESCRIPTOR' : _FHDFS_STOREDATA_RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:fhdfs_storedata_response)
  })
_sym_db.RegisterMessage(fhdfs_storedata_response)

fragment_status_response = _reflection.GeneratedProtocolMessageType('fragment_status_response', (_message.Message,), {
  'DESCRIPTOR' : _FRAGMENT_STATUS_RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:fragment_status_response)
  })
_sym_db.RegisterMessage(fragment_status_response)

header = _reflection.GeneratedProtocolMessageType('header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:header)
  })
_sym_db.RegisterMessage(header)

recode_fragments_request = _reflection.GeneratedProtocolMessageType('recode_fragments_request', (_message.Message,), {
  'DESCRIPTOR' : _RECODE_FRAGMENTS_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:recode_fragments_request)
  })
_sym_db.RegisterMessage(recode_fragments_request)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST_TYPE._serialized_start=888
  _REQUEST_TYPE._serialized_end=1005
  _STOREDATA_REQUEST._serialized_start=18
  _STOREDATA_REQUEST._serialized_end=55
  _GETDATA_REQUEST._serialized_start=57
  _GETDATA_REQUEST._serialized_end=92
  _FRAGMENT_STATUS_REQUEST._serialized_start=94
  _FRAGMENT_STATUS_REQUEST._serialized_end=142
  _STORAGENODE._serialized_start=144
  _STORAGENODE._serialized_end=183
  _TASK11REQUEST._serialized_start=185
  _TASK11REQUEST._serialized_end=238
  _TASK11RESPONSE._serialized_start=240
  _TASK11RESPONSE._serialized_end=273
  _TASK12REQUEST._serialized_start=275
  _TASK12REQUEST._serialized_end=369
  _TASK12RESPONSE._serialized_start=371
  _TASK12RESPONSE._serialized_end=404
  _FHDFS_STOREDATA_REQUEST._serialized_start=406
  _FHDFS_STOREDATA_REQUEST._serialized_end=514
  _HEARTBEATRESPONSE._serialized_start=516
  _HEARTBEATRESPONSE._serialized_end=566
  _FHDFS_STOREDATA_RESPONSE._serialized_start=568
  _FHDFS_STOREDATA_RESPONSE._serialized_end=632
  _FRAGMENT_STATUS_RESPONSE._serialized_start=634
  _FRAGMENT_STATUS_RESPONSE._serialized_end=735
  _HEADER._serialized_start=737
  _HEADER._serialized_end=782
  _RECODE_FRAGMENTS_REQUEST._serialized_start=784
  _RECODE_FRAGMENTS_REQUEST._serialized_end=886
# @@protoc_insertion_point(module_scope)
